### Authorization by token, part 1. Retrieve and save token.
POST http://localhost:7000/api/login
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "test"
}

> {% client.global.set("auth_token", response.body.data.jwt); %}

### Authorization by token, part 2. Use token to authorize.
POST http://localhost:7000/api/carry
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "user_id": 15,
  "year": "2020-01-01",
  "saldo_hours": 15,
  "saldo_minutes": 27,
  "saldo_positive": true,
  "holidays": 30,
  "holidays_previous": 14
}

###