### Authorization by token, part 1. Retrieve and save token.
POST http://localhost:7000/api/login
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "test"
}

> {% client.global.set("auth_token", response.body.data.jwt); %}

### Authorization by token, part 2. Use token to authorize.
GET http://localhost:7000/api/carry
Authorization: Bearer {{auth_token}}
Accept: application/json
###